name: Deploy Development Infrastructure

on:
  workflow_call:
    outputs:
      rest_api_endpoint: 
        value: ${{ jobs.deploy_development_infrastructure.outputs.rest_api_endpoint }}
      rest_api_key: 
        value: ${{ jobs.deploy_development_infrastructure.outputs.rest_api_key }}
      bucket_name: 
        value: ${{ jobs.deploy_development_infrastructure.outputs.bucket_name }}
      website_url:
        value: ${{ jobs.deploy_development_infrastructure.outputs.cloudfront_domain_name }}
      frontend_automation_aws_role:
        value: ${{ jobs.deploy_development_infrastructure.outputs.frontend_automation_aws_role }}

jobs:
  deploy_development_infrastructure:
    runs-on: ubuntu-latest
    environment: development
    env:
      TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
      TF_WORKSPACE: personal-website-infrastructure-development-${{ github.repository_id }}-${{ github.event.number }}
      
    steps:
      - name: Create new Terraform workspace
        id: create-new-terraform-workspace
        run: |
          RESULT=$(curl \
          -X POST \
          -H "Authorization: Bearer ${{ secrets.TF_API_TOKEN }}" \
          -H "Content-Type: application/vnd.api+json" \
          -d '{
                "data": {
                  "type": "workspace",
                  "attributes": {
                    "name": "${{ env.TF_WORKSPACE }}"
                  }
                }
              }' \
          https://app.terraform.io/api/v2/organizations/${{ env.TF_CLOUD_ORGANIZATION }}/workspaces)
          echo "result=$RESULT" >> "$GITHUB_OUTPUT"

      - name: Add AWS role to Terraform cloud workspace
        if: fromJson(steps.create-new-terraform-workspace.outputs.result).data
        run: |
          curl \
          -X POST \
          -H "Authorization: Bearer ${{ secrets.TF_API_TOKEN }}" \
          -H "Content-Type: application/vnd.api+json" \
          -d '{
                "data": {
                  "type": "vars",
                  "attributes": {
                    "key": "TFC_AWS_RUN_ROLE_ARN",
                    "value": "${{ secrets.TFC_AWS_RUN_ROLE_ARN }}",
                    "category": "env",
                    "sensitive": true
                  }
                }
              }' \
          https://app.terraform.io/api/v2/workspaces/${{ fromJson(steps.create-new-terraform-workspace.outputs.result).data.id }}/vars

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: huynhlkevin/personal-website-infrastructure

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false

      - name: Terraform Output
        id: terraform-output
        run: terraform output -json

    outputs:
      rest_api_endpoint: ${{ fromJson(steps.terraform-output.outputs.stdout).rest_api_invoke_url.value }}
      rest_api_key: ${{ fromJson(steps.terraform-output.outputs.stdout).rest_api_key.value }}
      bucket_name: ${{ fromJson(steps.terraform-output.outputs.stdout).bucket_name.value }}
      cloudfront_domain_name: ${{ fromJson(steps.terraform-output.outputs.stdout).cloudfront_domain_name.value }}
      frontend_automation_aws_role: ${{ fromJson(steps.terraform-output.outputs.stdout).frontend_automation_role_name.value }}