name: Destroy Development Infrastructure

on:
  workflow_call:
      
jobs:
  destroy_development_infrastructure:
    runs-on: ubuntu-latest
    environment: development
    env:
      TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
      TF_WORKSPACE: personal-website-infrastructure-development-${{ github.repository_id }}-${{ github.event.number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: huynhlkevin/personal-website-infrastructure

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false

      - name: Wait before attempting to delete the workspace so it can update its state
        run: sleep 300

      - name: Delete Terraform workspace
        run: |
          curl \
          -X POST \
          -H "Authorization: Bearer ${{ secrets.TF_API_TOKEN }}" \
          -H "Content-Type: application/vnd.api+json" \
          https://app.terraform.io/api/v2/organizations/${{ env.TF_CLOUD_ORGANIZATION }}/workspaces/${{ env.TF_WORKSPACE }}/actions/safe-delete