name: Development

on:
  pull_request:
    types: [opened, closed, synchronize]

jobs:
  deploy_development_infrastructure:
    if: !github.event.pull_request.merged
    uses: ./.github/workflows/deploy-development-infrastructure.yml
    secrets: inherit

  deploy_website_content:
    uses: huynhlkevin/personal-website/.github/workflows/deploy-website-content.yml@master
    needs: [deploy_development_infrastructure]
    secrets: inherit
    permissions:
      id-token: write
    with:
      rest_api_endpoint: ${{ needs.deploy_development_infrastructure.outputs.rest_api_endpoint }}
      rest_api_key: ${{ needs.deploy_development_infrastructure.outputs.rest_api_key }}
      bucket_name: ${{ needs.deploy_development_infrastructure.outputs.bucket_name }}
      frontend_automation_aws_role: ${{ needs.deploy_development_infrastructure.outputs.frontend_automation_aws_role }}
      production: false

  destroy_development_infrastructure:
    if: github.event.pull_request.merged
    uses: ./.github/workflows/destroy-development-infrastructure.yml
    secrets: inherit