name: Development

on:
  pull_request:

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

  deploy_development_infrastructure:
    uses: ./.github/workflows/deploy-development-infrastructure.yml
    secrets: inherit
    with:
      tf_workspace: personal-website-infrastructure-${{ github.ref_name }}

  deploy_website_content:
    uses: huynhlkevin/personal-website/.github/workflows/deploy-website-content.yml@master
    needs: [deploy_development_infrastructure]
    secrets: inherit
    permissions:
      id-token: write
    with:
      rest_api_endpoint: ${{ needs.deploy_development_infrastructure.outputs.rest_api_endpoint }}
      rest_api_key: ${{ needs.deploy_development_infrastructure.outputs.rest_api_key }}
      bucket_name: ${{ needs.deploy_development_infrastructure.outputs.bucket_name }}
      production: false

  destroy_development_infrastructure:
    if: ${{ github.event.pull_request.merged }}
    uses: ./.github/workflows/destroy-development-infrastructure.yml
    secrets: inherit
    with:
      tf_workspace: personal-website-infrastructure-${{ github.ref_name }}