name: Development

on:
  pull_request:

jobs:
  deploy_development_infrastructure:
    uses: ./.github/workflows/deploy_development_infrastructure.yml
    secrets: inherit

  deploy_frontend:
    uses: huynhlkevin/personal-website/.github/workflows/deploy.yml@master
    needs: [deploy_development_infrastructure]
    secrets: inherit
    permissions:
      id-token: write
    with:
      rest_api_endpoint: ${{ needs.deploy_development_infrastructure.outputs.rest_api_endpoint }}
      rest_api_key: ${{ needs.deploy_development_infrastructure.outputs.rest_api_key }}
      bucket_name: ${{ needs.deploy_development_infrastructure.outputs.bucket_name }}
    
