name: Production

on:
  push:
    branches: 
      - main

jobs:
  deploy-production-infrastructure:
    uses: ./.github/workflows/deploy-production-infrastructure.yaml
    secrets: inherit

  deploy-website-content:
    uses: huynhlkevin/personal-website/.github/workflows/deploy-website-content.yaml@master
    needs: [deploy-production-infrastructure]
    secrets: inherit
    permissions:
      id-token: write
    with:
      production: true

  run-tests-on-website:
    uses: huynhlkevin/personal-website/.github/workflows/run-tests-on-website.yaml@master
    needs: [deploy-website-content]
    with:
      website_url: www.huynhlkevin.com    
