name: Production

on:
  push:
    branches: [ "main" ]

jobs:
  destroy_development_infrastructure:
    uses: ./.github/workflows/destroy_development_infrastructure.yml
    secrets: inherit

  deploy_production_infrastructure:
    uses: ./.github/workflows/deploy_production_infrastructure.yml
    secrets: inherit
