name: Production

on:
  push:
    branches: [main]

jobs:
  deploy_production_infrastructure:
    uses: ./.github/workflows/deploy-production-infrastructure.yaml
    secrets: inherit

  deploy_website_content:
    uses: huynhlkevin/personal-website/.github/workflows/deploy-website-content.yaml@master
    needs: [deploy_production_infrastructure]
    secrets: inherit
    permissions:
      id-token: write
    with:
      production: true

  run_tests_on_website:
    uses: huynhlkevin/personal-website/.github/workflows/run-tests-on-website.yaml@master
    needs: [deploy_website_content]
    with:
      website_url: www.huynhlkevin.com    
